### ISSUE TITLE
A Support link like Buy me a coffee or github sponsors so some of us can support your great work 💰️💰️💰️

### ISSUE THREAD

**Issue by tallguyjenks** [ryanjamurphy/review-obsidian#10]
![image](https://user-images.githubusercontent.com/29872822/99885715-d6717200-2beb-11eb-9437-595c5f2538de.png)

**Comment by ryanjamurphy** [comment]
Thanks! That's kind of you.

I've considered it, of course. However, this stuff is somewhat related to my research interests, and I'm (very fortunately) receiving a scholarship in my PhD. So, for now, consider my work publicly funded and send some appreciation to Canada's tri-council research agencies. 😉

**Comment by tallguyjenks** [comment]
![image](https://user-images.githubusercontent.com/29872822/99886214-a330e200-2bef-11eb-96a0-2778e90e973a.png)
