### ISSUE TITLE
Compatability with Templator

### ISSUE THREAD

**Issue by uwidev** [ryanjamurphy/review-obsidian#21]
Would it be possible to have the template be created from Templator rather than the default Template plugin?

**Comment by meskill** [comment]
I think you meant [Templater](https://github.com/SilentVoid13/Templater) plugin

I'm using both plugins and it works fine except for templates based on title - see https://github.com/ryanjamurphy/review-obsidian/issues/22

**Comment by ryanjamurphy** [comment]
Closing this to keep discussion in #22!
