### ISSUE TITLE
Feature request to make certain note or a block reoccurring

### ISSUE THREAD

**Issue by jaideeprana** [ryanjamurphy/review-obsidian#23]
This feature request is similar to how Google's calendar's reoccurring works.

I want to customise a particular note reviewal cycle.

For e.g. I want my Health note to be reviewed by me every Friday.

Similarly some other notes fortnightly, monthly etc.

**Comment by Mara-Li** [comment]
You can check Slated, who done that ! https://github.com/tgrosinger/slated-obsidian

**Comment by jaideeprana** [comment]
Thanks @Mara-Li
