### ISSUE TITLE
Not able to find 'Your daily notes folder' in plugin settings

### ISSUE THREAD

**Issue by j-peeters** [ryanjamurphy/review-obsidian#24]
From the instructions on GitHub:
> Make sure you _review_ the plugin's settings to assign:
> -   Your daily notes folder (defaults to `/`)

I'm not able to find this in the plugins settings. Is this obsolete?

**Comment by ryanjamurphy** [comment]
Sorry, it is. It just uses your daily notes (or Periodic Notes, if you're using it) settings now!

**Comment by j-peeters** [comment]
Terrific, thanks for the speedy reply @ryanjamurphy.
