### ISSUE TITLE
Date format problem

### ISSUE THREAD

**Issue by Nebucatnetzer** [ryanjamurphy/review-obsidian#3]
I'm getting the following error when I try to run to set the review date, the Natural Language Date plugin works fine.
``` js
Current format: YYYY-MM-DD
main.ts:164 Uncaught TypeError: _this.getDateString is not a function
    at NaturalLanguageDates.processDate (eval at <anonymous> (app.js:1), <anonymous>:5097:26)
    at Review.setReviewDate (eval at <anonymous> (app.js:1), <anonymous>:128:46)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:209:60)
    at HTMLButtonElement.<anonymous> (app.js:1)
```

**Comment by ryanjamurphy** [comment]
Hm. I am not able to reproduce the error... What settings do you have in the Natural Language Date plugin settings?

**Comment by ryanjamurphy** [comment]
You may want to double-check that you've updated both Natural Language Dates plugin (0.2.6 is the current version) and Review (1.3.0 is the current version).

**Comment by Nebucatnetzer** [comment]
Hm strange got it working now.
Update your plugin (NLD was already up to date) but that didn't work.
Restarted Obsidian and then Review complained that NLD was missing.
Toggled both plugins and now it's working.
No idea what when wrong there ¯\_(ツ)_/¯.
