### ISSUE TITLE
Choose where to add the note

### ISSUE THREAD

**Issue by almajbary** [ryanjamurphy/review-obsidian#30]
How can I choose where to add the new note, as my daily note folder name is different it's like this 0. Daily Notes/Daily, so whenever I use a review it creates a new folder with Daily Notes/Daily.

What I wish I can do to select the path of my daily notes. 

and thank you so much for this great plugin, it's awesome. :-)

**Comment by ryanjamurphy** [comment]
Hiya! It should use your daily note preferences —have you configured that in Preferences → Daily Note (or Periodic Notes, if you are using that plugin).

**Comment by almajbary** [comment]
Many thanks, that fixed the issue :) I forgot to config my periodic notes preference.
