### ISSUE TITLE
Crash on ios when engaging review 

### ISSUE THREAD

**Issue by daxmonson** [ryanjamurphy/review-obsidian#31]
Working great on osx, but on ios when selecting add block or page to review Obs hangs then it crashes. There's no console obviously on ios so wondering if there's any way I can help you figure it out?  
Thanks for the stellar plugin btw.

**Comment by ryanjamurphy** [comment]
Hmm. I couldn't reproduce this just now on mobile 1.13.1, iOS 16.

There are ways to log console errors on mobile. I used this previously, but haven't tried it in a while: https://github.com/shabegom/obsidian-mobile-logging

- Install it via BRAT (https://github.com/TfTHacker/obsidian42-brat) 
- Create a note called `Log` 
- reproduce the issue then copy+paste `Log`'s contents

Hopefully that works?

**Comment by daxmonson** [comment]
Very interesting. As soon as I installed the mobile console log via brat and toggled it on then engaged review it's now not freezing. I had forced closed Obs on ios and restarted the device a couple of times too. Handy to know about that little known plugin too. Something worked. Thanks
