### ISSUE TITLE
Link path to subfolder

### ISSUE THREAD

**Issue by Fiveflower** [ryanjamurphy/review-obsidian#4]
Hello ryanjamurphy,

I like the Plugin, it´s a good possibility to work well on follow-ups.
But on thing, that doesn´t work for me are subfolders. The links are put in the date-file under the Topic ## review - so far so good. But they only point to the root path, and don´t follow the complete path to the note the review was executed.  Any idea for that?

**Comment by ryanjamurphy** [comment]
Hiya! The folder needs to exist first—the plugin doesn't handle folder/subfolder creation. Sorry!

**Comment by Fiveflower** [comment]
….. error identified. My notes startet with a "#", so the link wasn´t found generally --> my bad…..
Issue closed -> Keep up the good work!
