### ISSUE TITLE
Default date (with customizability)

### ISSUE THREAD

**Issue by ryanjamurphy** [ryanjamurphy/review-obsidian#5]
> I was just thinking about a custom default date. E.g. Monday because the default tomorrow doesn't actually work.
Maybe the two ideas are related?

_Originally posted by @Nebucatnetzer in https://github.com/ryanjamurphy/review-obsidian/issues/1#issuecomment-724295793_

**Comment by ryanjamurphy** [comment]
[Also from @Nebucatnetzer:](https://github.com/ryanjamurphy/review-obsidian/issues/1#issuecomment-724983376)
> I thought it might work like this:
> 
> Configure a default date in the settings e.g. "monday".
> Go to a note.
> Start the review command.
> Don't enter anything and press enter.
> Review then uses the default date from the settings.
> If the user enters something in the input field Review then uses the date from the input.

**Comment by ryanjamurphy** [comment]
Implemented in 1.4.0, just released!

**Comment by Nebucatnetzer** [comment]
Just noticed something minor here.
Even though I've configured a default date (which is working just fine) it still says "tomorrow" in the pop-up.
It might be a better user experience if the text in the pop-up would match the day the user configured.

**Comment by ryanjamurphy** [comment]
@Nebucatnetzer Great catch. This is fixed (and the _default_ default date is now tomorrow, so that'll show unless you change it.)

**Comment by Nebucatnetzer** [comment]
Great thank you :D
