### ISSUE TITLE
prefix '-' or '- [ ]' doesn't work

### ISSUE THREAD

**Issue by kabo1234** [ryanjamurphy/review-obsidian#9]
Hi Ryan,

the prefix doesn't seem to do anything - I tried it both with custom CSS and the standard Obsidian CSS. 

Great plugin anyway!

**Comment by ryanjamurphy** [comment]
Thanks! I did this deliberately, but now I see it might not have been a good idea. I'll provide a setting for users to specify what kind of block link/embed they want via prefixes when I get back to my desk.

**Comment by ryanjamurphy** [comment]
Oh, wait. Does the prefix not work with note links at all? In my above comment I was referring to block links, but maybe I introduced a regression in prefix handling in 1.5.0...

**Comment by ryanjamurphy** [comment]
This is now fixed. You can customize the prefix you want to use in the plugin's settings. Thanks!
